name: "Test Code runs"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Test Run
      run: |
        node index.js